baseURL = "http://gohugo.io/"
title = "H3iND33R's Public Docker"
languageCode = "en-us"
theme = ['github.com/akopdev/hugo-theme-chicago7']
pagination.pagerSize = 10

[permalinks]
posts = "/posts/:year:month:day"

[markup]
[markup.highlight]
style = "bw"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.header]]
name = "Publications"
url = "publications"
weight = 30

[[menu.header]]
name = "Projects"
url = "projects"
weight = 20

[[menu.header]]
name = "Home"
url = "/"
weight = 10

[params]
# Optional. The relative path to the site logo file within the `assets/` folder
logo = "logo.svg"

# Favicon
favicon = "favicon.svg"

# Web site author for copyrighting
author = "H3iND33R"

[params.social]
twitter = "https://x.com/h3in_upsider"
instagram = "https://instagram.com/y__jwns52"
facebook = "https://facebook.com/profile.php?id=100059439313056&locale=ko_KR"
linkedin = "https://www.linkedin.com/in/%EC%A4%80%EC%84%9D-%EC%97%AC-8b680534b/"